# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token corrigido para METRICS_TOKEN
          token: ${{ secrets.METRIC_TOKEN }}

          # Opções
          user: rodrigojsfreitas
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugins
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Repositórios
          plugin_repositories: yes
          plugin_repositories_forks: yes  # 👈 ADICIONADO: Para incluir seus forks

          # Linguagens
          plugin_languages: yes
          plugin_languages_indepth: yes  # 👈 ADICIONADO: Para análise profunda
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          
          # Tráfego (se você tiver um repositório popular)
          plugin_traffic: yes
